version: '3.6'
services:

  mongodb:
    image: mongo:latest
    container_name: "api-database"
    ports:
      - "27017:27017"
      - "27018:27018"
    networks:
      - ueAPI-network

  rabbitmq:
    image: rabbitmq:latest
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - ueAPI-network
    depends_on:
      - mongodb

  user_events_api:
    build: ./user-events-api
    ports:
      - "8080:8080"
    links:
      - mongodb
    depends_on:
      - rabbitmq
    restart: unless-stopped
    networks:
      - ueAPI-network

  events_worker:
    build: ./events-worker
    ports:
      - "8090:8090"
    links:
      - mongodb
    depends_on:
      - user_events_api
    restart: unless-stopped
    networks:
      - ueAPI-network

networks:
  ueAPI-network:
    driver: bridge
volumes:
  dbdata:
